#let title = "upsi"
#let subtitle = "A Decentralized STI Tracing Approach"
#let thesis = "Bachelor Thesis"
#let semester = "Spring 2024"
#let author = "Laurin Zubler"
#let advisor = "Dr. Thomas Bocek"
#let institute = "Distributed Systems and Ledgers Lab"
#let fieldOfStudy = "Software Engineering"
